version: '3.1'

services:
  database:
    image: "postgres"
    environment:
      - POSTGRES_DB=xmlfeed
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=xmlfeedpass
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  redis:
    image: "redis:latest"
    container_name: "redis-xmlfeed"
    ports:
      - "6379:6379"
  mongo:
    image: "mongo"
    container_name: "mongo_container_xmlfeed"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=xmlfeed
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=xmlfeedpass
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    container_name: small_es
    environment:
      - ELASTICSEARCH_USERNAME=elasticsearch
      - ELASTICSEARCH_PASSWORD=elasticsearch
      - node.name=es
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "path.repo=/tmp"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
volumes:
  database-data:
