# Generated by Django 3.2.5 on 2022-09-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_marketplace_delivery_man'),
        ('orders', '0048_alter_orderexportfilters_state'),
        ('beez', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beez',
            new_name='BeezCarrier',
        ),
    ]
