# Generated by Django 3.2.5 on 2022-09-15 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0043_alter_carrier_carrier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('responsable', models.CharField(max_length=100, verbose_name='Responsable')),
                ('tel', models.CharField(max_length=100, verbose_name='Phone')),
                ('email', models.EmailField(max_length=300, verbose_name='Email')),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='Fournisseurs/')),
                ('rib', models.CharField(blank=True, max_length=150, null=True)),
                ('mf', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('nb_colis', models.IntegerField(blank=True, null=True)),
                ('tentative', models.IntegerField(blank=True, null=True)),
                ('petit_livraison', models.FloatField(blank=True, default=0, null=True)),
                ('petit_retour', models.FloatField(blank=True, default=0, null=True)),
                ('grand_livraison', models.FloatField(blank=True, default=0, null=True)),
                ('grand_retour', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adresse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.address', verbose_name='Address')),
            ],
        ),
    ]
