# Generated by Django 3.2.5 on 2022-09-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketplace',
            old_name='adresse',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='marketplace',
            old_name='grand_livraison',
            new_name='high_delivery',
        ),
        migrations.RenameField(
            model_name='marketplace',
            old_name='grand_retour',
            new_name='high_return',
        ),
        migrations.RenameField(
            model_name='marketplace',
            old_name='petit_livraison',
            new_name='low_delivery',
        ),
        migrations.RenameField(
            model_name='marketplace',
            old_name='petit_retour',
            new_name='low_return',
        ),
        migrations.RenameField(
            model_name='marketplace',
            old_name='nb_colis',
            new_name='nb_order',
        ),
        migrations.RenameField(
            model_name='marketplace',
            old_name='tel',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='marketplace',
            name='responsable',
        ),
        migrations.AddField(
            model_name='marketplace',
            name='responsible',
            field=models.CharField(default=1, max_length=100, verbose_name='Responsible'),
            preserve_default=False,
        ),
    ]
