# Generated by Django 3.2.5 on 2022-09-15 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_delete_marketplace'),
        ('marketplace', '0002_auto_20220915_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='delivery_man',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.carrier'),
        ),
    ]
