# Generated by Django 3.2.5 on 2023-05-15 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0058_auto_20230515_1658'),
        ('marketplace', '0004_alter_marketplace_delivery_man'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activiter', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='marketplace',
            name='address',
        ),
        migrations.RemoveField(
            model_name='marketplace',
            name='delivery_man',
        ),
        migrations.RemoveField(
            model_name='marketplace',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='marketplace',
            name='responsible',
        ),
        migrations.AddField(
            model_name='marketplace',
            name='adress',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketplace',
            name='cite',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.cite', verbose_name='Cite'),
        ),
        migrations.AddField(
            model_name='marketplace',
            name='code_postale',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='marketplace',
            name='commercial',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fournisseur_commercial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketplace',
            name='delegation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.delegation', verbose_name='Delegation'),
        ),
        migrations.AddField(
            model_name='marketplace',
            name='filiere',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.filliere', verbose_name='filiere'),
        ),
        migrations.AddField(
            model_name='marketplace',
            name='responsable',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='marketplace',
            name='stock_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketplace',
            name='tel',
            field=models.CharField(default=216, max_length=100),
        ),
        migrations.AddField(
            model_name='marketplace',
            name='ville',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.ville', verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='email',
            field=models.EmailField(max_length=300),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='high_delivery',
            field=models.FloatField(blank=True, default=11, null=True),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='high_return',
            field=models.FloatField(blank=True, default=6, null=True),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='low_delivery',
            field=models.FloatField(blank=True, default=8, null=True),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='low_return',
            field=models.FloatField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='nb_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='tentative',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.CreateModel(
            name='FinanceMarketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('nombre_de_colis', models.IntegerField(blank=True, default=0, null=True)),
                ('total_cod', models.FloatField(blank=True, default=0, null=True)),
                ('total_hfl', models.FloatField(blank=True, default=0, null=True)),
                ('cous_livraison', models.FloatField(blank=True, default=0, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('marketplace', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.marketplace')),
            ],
        ),
        migrations.AddField(
            model_name='marketplace',
            name='secteur',
            field=models.ManyToManyField(related_name='fournisseur_secteur', to='marketplace.Secteur'),
        ),
    ]
