# Generated by Django 3.2.5 on 2023-05-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_auto_20230515_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='secteur',
            field=models.ManyToManyField(default=None, related_name='fournisseur_secteur', to='marketplace.Secteur'),
        ),
    ]
