# Generated by Django 3.2.5 on 2023-05-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_marketplace_secteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='secteur',
            field=models.ManyToManyField(default=None, null=True, related_name='fournisseur_secteur', to='marketplace.Secteur'),
        ),
    ]
