# Generated by Django 3.2.5 on 2023-05-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_alter_marketplace_secteur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketplace',
            old_name='tel',
            new_name='phone',
        ),
    ]
