# Generated by Django 3.2.5 on 2023-05-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_rename_adress_marketplace_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='secteur',
            field=models.ManyToManyField(choices=[('produit bio', 'produit bio'), ('textile', 'textile'), ('Divers', 'Divers')], related_name='fournisseur_secteur', to='marketplace.Secteur'),
        ),
    ]
