# Generated by Django 3.2.5 on 2021-09-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210915_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='avatar'),
        ),
    ]
