# Generated by Django 3.2.5 on 2021-09-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_light',
            field=models.BooleanField(default=False),
        ),
    ]
