# Generated by Django 3.2.5 on 2021-10-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_is_light'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
