# Generated by Django 3.2.5 on 2021-11-04 16:52

from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0015_auto_20211104_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='GsoShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=20)),
                ('account_number', models.IntegerField(verbose_name='Account number')),
                ('service_code', models.CharField(default='CPS', max_length=5, verbose_name='Service Code')),
                ('scheduled_ship_date', models.CharField(blank=True, default=None, max_length=11, null=True, verbose_name='Scheduled Ship Date')),
                ('scheduled_delivery_date', models.CharField(blank=True, default=None, max_length=11, null=True, verbose_name='Scheduled Delivery Date')),
                ('scheduled_delivery_time', models.CharField(blank=True, default=None, max_length=11, null=True, verbose_name='Scheduled Delivery Time')),
                ('delivery_zone', models.IntegerField(blank=True, default=None, null=True, verbose_name='Delivery Zone based on Origin and Destination zip code')),
                ('transportation_charge', models.FloatField(blank=True, default=None, null=True, verbose_name='Service charge for shipment.')),
                ('cod_charge', models.FloatField(blank=True, default=None, null=True, verbose_name='Charge applicable to COD shipments.')),
                ('insurance_charge', models.FloatField(blank=True, default=None, null=True, verbose_name='Charge applicable to Insured shipments.')),
                ('fuel_surcharge', models.FloatField(blank=True, default=None, null=True, verbose_name='Fuel surcharge for shipment.')),
                ('other_charge', models.TextField(blank=True, default=None, null=True, verbose_name='Accessorial charges applicable to shipment.')),
                ('total_charge', models.FloatField(blank=True, default=None, null=True, verbose_name='Total charge for shipment.')),
                ('paper_label', models.FileField(blank=True, default=None, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='', verbose_name='PNG file label')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order')),
            ],
        ),
    ]
