# Generated by Django 3.2.5 on 2022-09-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_marketplace_delivery_man'),
        ('orders', '0048_alter_orderexportfilters_state'),
        ('colissimo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colissimo',
            new_name='ColissimoCarrier',
        ),
    ]
