# Generated by Django 3.2.5 on 2021-10-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreadcrumbModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='SKU')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='SKU')),
            ],
        ),
    ]
