# Generated by Django 3.2.5 on 2021-10-07 18:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20211007_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadcrumbmodel',
            name='utility',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None),
        ),
    ]
