# Generated by Django 3.2.5 on 2021-09-23 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Number', models.IntegerField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('Customer_Name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer_Name')),
                ('Customer_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Customer_email')),
                ('Company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company')),
                ('Street_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street_1')),
                ('Street_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street_2')),
                ('Zip_Code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Zip_Code')),
                ('State', models.CharField(blank=True, max_length=255, null=True, verbose_name='State')),
                ('City', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('Phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_order_item_id', models.IntegerField(blank=True, default=None, null=True)),
                ('sku', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
