# Generated by Django 3.2.5 on 2021-10-22 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20211022_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordernotes',
            old_name='notes',
            new_name='order',
        ),
    ]
