# Generated by Django 3.2.5 on 2021-10-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rename_notes_ordernotes_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='substatus',
            field=models.CharField(blank=True, choices=[('UC', 'Uncategorized'), ('OC', 'Out of stock')], default='NO', max_length=255, null=True, verbose_name='status'),
        ),
    ]
