# Generated by Django 3.2.5 on 2021-11-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_substatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Customer_Name',
            new_name='customer_Name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Customer_email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='State',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Street_1',
            new_name='street_1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Street_2',
            new_name='street_2',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Zip_Code',
            new_name='zip_Code',
        ),
    ]
