# Generated by Django 3.2.5 on 2021-11-04 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20211103_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(choices=[('gso', 'GSO'), ('ups', 'UPS')], max_length=100, verbose_name='Carrier')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('account_number', models.CharField(max_length=255, verbose_name='Account number')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='substatus',
            field=models.CharField(blank=True, choices=[('UC', 'Uncategorized'), ('OC', 'Out of stock')], default='', max_length=255, null=True, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='GSOCarrier',
            fields=[
                ('carrier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.carrier')),
                ('username', models.CharField(max_length=100, verbose_name='GSO Username')),
                ('password', models.CharField(max_length=255, verbose_name='GSO Password')),
            ],
            bases=('orders.carrier',),
        ),
    ]
