# Generated by Django 3.2.5 on 2021-11-04 15:17

from django.db import migrations, models
import utils.s3


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20211104_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_shipment_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='label',
            field=models.FileField(default='', storage=utils.s3.PrivateMediaStorage(), upload_to='order_label'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Tracking code'),
        ),
    ]
