# Generated by Django 3.2.5 on 2021-11-04 15:54

from django.db import migrations, models
import django.db.models.deletion
import utils.s3


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20211104_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, default='', max_length=255, verbose_name='Company')),
                ('telephone', models.CharField(default='(619) 663-4134', max_length=100, verbose_name='Telephone')),
                ('street_address', models.CharField(max_length=255, verbose_name='Street Address')),
                ('address_line_2', models.CharField(blank=True, default='', max_length=150, verbose_name='Address Line 2')),
                ('zipcode', models.CharField(max_length=15, verbose_name='Postal/Zip code')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('state', models.CharField(max_length=255, verbose_name='State/Province/Region')),
            ],
        ),
        migrations.AddField(
            model_name='carrier',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='label',
            field=models.FileField(blank=True, null=True, storage=utils.s3.PrivateMediaStorage(), upload_to='order_label'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='sender_address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='orders.address', verbose_name='Sender address'),
            preserve_default=False,
        ),
    ]
