# Generated by Django 3.2.5 on 2021-11-09 15:50

from django.db import migrations, models
import django.db.models.deletion
import utils.s3


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20211104_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('AC', 'ACTION REQUIRED'), ('NO', 'NEW ORDER'), ('Co', 'CONFIRMED'), ('Pr', 'PRINTED'), ('Pa', 'PACKED'), ('OS', 'Shipped'), ('D', 'COMPLETED'), ('F', 'PROBLEMS'), ('awaiting_shipment', 'Awaiting for shipment')], default='NO', max_length=255, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='substatus',
            field=models.CharField(blank=True, choices=[('UC', 'Uncategorized'), ('OC', 'Out of stock'), ('PT', 'PRE TRANSIT'), ('IT', 'IN TRANSIT')], default='', max_length=255, null=True, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='TrackingActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('happened_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_type', models.CharField(choices=[('in_transit', 'in_transit'), ('exception', 'exception'), ('delivery', 'delivery')], max_length=100)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('label', models.FileField(blank=True, default=None, null=True, storage=utils.s3.PrivateMediaStorage(), upload_to='')),
                ('order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
