# Generated by Django 3.2.5 on 2021-11-21 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20211109_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='carrier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.carrier'),
        ),
    ]
