# Generated by Django 3.2.5 on 2021-11-21 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_shipment_carrier'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderExportFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('AC', 'ACTION REQUIRED'), ('NO', 'NEW ORDER'), ('Co', 'CONFIRMED'), ('Pr', 'PRINTED'), ('Pa', 'PACKED'), ('OS', 'Shipped'), ('D', 'COMPLETED'), ('F', 'PROBLEMS'), ('awaiting_shipment', 'Awaiting for shipment')], default='NO', max_length=255, null=True, verbose_name='status')),
                ('percentage', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderExportFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(blank=True, choices=[('AC', 'ACTION REQUIRED'), ('NO', 'NEW ORDER'), ('Co', 'CONFIRMED'), ('Pr', 'PRINTED'), ('Pa', 'PACKED'), ('OS', 'Shipped'), ('D', 'COMPLETED'), ('F', 'PROBLEMS'), ('awaiting_shipment', 'Awaiting for shipment')], default='NO', max_length=255, null=True, verbose_name='order status')),
                ('creation_date_start', models.DateTimeField(auto_now_add=True)),
                ('creation_date_finish', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=2, null=True, verbose_name='State')),
                ('carrier', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.carrier')),
            ],
        ),
    ]
