# Generated by Django 3.2.5 on 2021-11-21 14:18

from django.db import migrations, models
import django.db.models.deletion
import utils.s3


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_orderexportfiles_orderexportfilters'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderexportfiles',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, storage=utils.s3.PrivateMediaStorage(), upload_to='order_label'),
        ),
        migrations.AddField(
            model_name='orderexportfiles',
            name='filters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orderexportfilters'),
        ),
    ]
