# Generated by Django 3.2.5 on 2021-11-21 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0020_auto_20211121_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderexportfiles',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderexportfilters',
            name='creation_date_finish',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orderexportfilters',
            name='creation_date_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orderexportfilters',
            name='order_status',
            field=models.CharField(blank=True, choices=[('AC', 'ACTION REQUIRED'), ('NO', 'NEW ORDER'), ('Co', 'CONFIRMED'), ('Pr', 'PRINTED'), ('Pa', 'PACKED'), ('OS', 'Shipped'), ('D', 'COMPLETED'), ('F', 'PROBLEMS'), ('awaiting_shipment', 'Awaiting for shipment')], max_length=255, null=True, verbose_name='order status'),
        ),
        migrations.AlterField(
            model_name='orderexportfilters',
            name='state',
            field=models.CharField(blank=True, choices=[('AK', 'AK'), ('AL', 'AL'), ('AR', 'AR'), ('AZ', 'AZ'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DC', 'DC'), ('DE', 'DE'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('IA', 'IA'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('MA', 'MA'), ('MD', 'MD'), ('ME', 'ME'), ('MI', 'MI'), ('MN', 'MN'), ('MO', 'MO'), ('MT', 'MT'), ('NC', 'NC'), ('ND', 'ND'), ('NE', 'NE'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NV', 'NV'), ('NY', 'NY'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('Tn', 'Tn'), ('VA', 'VA'), ('VT', 'VT'), ('WA', 'WA'), ('WI', 'WI'), ('WV', 'WV'), ('WY', 'WY'), ('yy', 'yy')], max_length=2, null=True, verbose_name='State'),
        ),
    ]
