# Generated by Django 3.2.5 on 2021-11-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20211129_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderexportfiles',
            name='line_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
