# Generated by Django 3.2.5 on 2021-11-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_orderexportfiles_line_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderexportfiles',
            name='line_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
