# Generated by Django 3.2.5 on 2021-12-02 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211006_1618'),
        ('orders', '0026_alter_orderitems_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='original_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
