# Generated by Django 3.2.5 on 2022-08-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20211207_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderexportfilters',
            name='state',
            field=models.CharField(blank=True, choices=[], max_length=2, null=True, verbose_name='State'),
        ),
    ]
