# Generated by Django 3.2.5 on 2022-08-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_alter_orderexportfilters_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderexportfilters',
            name='state',
            field=models.CharField(blank=True, choices=[('TN', 'TN')], max_length=2, null=True, verbose_name='State'),
        ),
    ]
