# Generated by Django 3.2.5 on 2022-09-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_alter_orderexportfilters_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingactivities',
            name='event_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderexportfilters',
            name='state',
            field=models.CharField(blank=True, choices=[('BA', 'BA'), ('TN', 'TN')], max_length=2, null=True, verbose_name='State'),
        ),
    ]
