# Generated by Django 3.2.5 on 2022-09-07 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20220907_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='FPCarrier',
            fields=[
                ('carrier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.carrier')),
                ('username', models.CharField(max_length=100, verbose_name='FP Username')),
                ('password', models.CharField(max_length=255, verbose_name='FP Password')),
            ],
            bases=('orders.carrier',),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='carrier',
            field=models.CharField(choices=[('gso', 'GSO'), ('fp', 'FP'), ('ups', 'UPS')], max_length=100, verbose_name='Carrier'),
        ),
    ]
