# Generated by Django 3.2.5 on 2022-09-07 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_auto_20220907_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activiter', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MarketPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=300)),
                ('code_postale', models.IntegerField(null=True)),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='Fournisseurs/')),
                ('rib', models.CharField(blank=True, max_length=150, null=True)),
                ('mf', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('nb_colis', models.IntegerField(blank=True, null=True)),
                ('tentative', models.IntegerField(blank=True, null=True)),
                ('petit_livraison', models.FloatField(blank=True, default=0, null=True)),
                ('petit_retour', models.FloatField(blank=True, default=0, null=True)),
                ('grand_livraison', models.FloatField(blank=True, default=0, null=True)),
                ('grand_retour', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adresse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.address')),
                ('secteur', models.ManyToManyField(related_name='fournisseur_secteur', to='orders.Secteur')),
            ],
        ),
    ]
