# Generated by Django 3.2.5 on 2022-09-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_marketplace_secteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplace',
            name='secteur',
        ),
        migrations.DeleteModel(
            name='Secteur',
        ),
    ]
