# Generated by Django 3.2.5 on 2022-09-08 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_auto_20220907_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplace',
            name='code_postale',
        ),
        migrations.AddField(
            model_name='order',
            name='marketplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.marketplace'),
        ),
        migrations.AlterField(
            model_name='orderexportfilters',
            name='state',
            field=models.CharField(blank=True, choices=[], max_length=2, null=True, verbose_name='State'),
        ),
    ]
