# Generated by Django 3.2.5 on 2022-09-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_auto_20220908_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='marketplace',
        ),
        migrations.AlterField(
            model_name='orderexportfilters',
            name='state',
            field=models.CharField(blank=True, choices=[('BA', 'BA'), ('TN', 'TN')], max_length=2, null=True, verbose_name='State'),
        ),
    ]
