# Generated by Django 3.2.5 on 2022-09-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_auto_20220908_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='code_postale',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
