# Generated by Django 3.2.5 on 2022-09-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_marketplace_code_postale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplace',
            name='code_postale',
        ),
    ]
