# Generated by Django 3.2.5 on 2022-09-08 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_remove_marketplace_code_postale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='adresse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='email',
            field=models.EmailField(max_length=300, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='responsable',
            field=models.CharField(max_length=100, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='tel',
            field=models.CharField(max_length=100, verbose_name='Phone'),
        ),
    ]
