# Generated by Django 3.2.5 on 2022-09-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_alter_carrier_carrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='carrier',
            field=models.CharField(choices=[('gso', 'GSO'), ('fp', 'FP'), ('ups', 'UPS'), ('colissimo', 'Colissimo'), ('beezit', 'Beez it')], max_length=100, verbose_name='Carrier'),
        ),
    ]
