# Generated by Django 3.2.5 on 2022-09-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_delete_marketplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderexportfilters',
            name='state',
            field=models.CharField(blank=True, choices=[('BA', 'BA'), ('TN', 'TN'), ('sd', 'sd'), ('so', 'so')], max_length=2, null=True, verbose_name='State'),
        ),
    ]
