# Generated by Django 3.2.5 on 2022-09-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_alter_orderexportfilters_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=60, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='orderexportfilters',
            name='state',
            field=models.CharField(blank=True, choices=[('BA', 'BA')], max_length=2, null=True, verbose_name='State'),
        ),
    ]
