# Generated by Django 3.2.5 on 2022-09-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_marketplace_delivery_man'),
        ('orders', '0048_alter_orderexportfilters_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='carrier',
            field=models.CharField(choices=[('fp', 'FP'), ('colissimo', 'Colissimo'), ('beezit', 'Beez it')], max_length=100, verbose_name='Carrier'),
        ),
        migrations.AlterField(
            model_name='orderexportfilters',
            name='state',
            field=models.CharField(blank=True, choices=[('Ben Arous', 'Ben Arous'), ('Ben arous', 'Ben arous')], max_length=60, null=True, verbose_name='State'),
        ),
        migrations.DeleteModel(
            name='GSOCarrier',
        ),
    ]
