# Generated by Django 3.2.5 on 2023-04-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_auto_20220920_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderexportfilters',
            name='state',
            field=models.CharField(blank=True, choices=[], max_length=60, null=True, verbose_name='State'),
        ),
    ]
