# Generated by Django 3.2.5 on 2023-04-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0050_alter_orderexportfilters_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderexportfilters',
            name='state',
            field=models.CharField(blank=True, choices=[('Ben arous', 'Ben arous')], max_length=60, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='trackingactivities',
            name='happened_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
