# Generated by Django 3.2.5 on 2023-05-01 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_marketplace_delivery_man'),
        ('orders', '0051_auto_20230424_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='marketplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.marketplace'),
        ),
        migrations.AlterField(
            model_name='orderexportfilters',
            name='state',
            field=models.CharField(blank=True, choices=[], max_length=60, null=True, verbose_name='State'),
        ),
    ]
