# Generated by Django 3.2.5 on 2023-05-15 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0057_alter_address_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street_1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street_2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='client_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='client_cite',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.cite', verbose_name='Cite'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_deligaiton',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.delegation', verbose_name='Delegation'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_ville',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.ville', verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_zipcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expiditeur_cite',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Exp_Cite', to='orders.cite'),
        ),
        migrations.AddField(
            model_name='order',
            name='expiditeur_deligaiton',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Exp_Delegation', to='orders.delegation'),
        ),
        migrations.AddField(
            model_name='order',
            name='expiditeur_ville',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Exp_Ville', to='orders.ville'),
        ),
        migrations.AddField(
            model_name='order',
            name='expiditeur_zipcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='livreur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.carrier', verbose_name='livreur'),
        ),
        migrations.CreateModel(
            name='Filliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.address', verbose_name='Address')),
            ],
        ),
    ]
