# Generated by Django 3.2.5 on 2023-05-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0059_auto_20230515_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='city',
            new_name='cite',
        ),
    ]
