# Generated by Django 3.2.5 on 2023-05-17 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0060_rename_city_address_cite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expiditeur_cite',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Exp_Cite', to='orders.cite'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expiditeur_deligaiton',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Exp_Delegation', to='orders.delegation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expiditeur_ville',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Exp_Ville', to='orders.ville'),
        ),
    ]
