# Generated by Django 3.2.5 on 2023-05-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0062_alter_carrier_sender_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=255, verbose_name='State/Province/Region'),
        ),
    ]
