# Generated by Django 3.2.5 on 2021-09-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255, unique=True, verbose_name='SKU')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='Brand')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Weight')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Price')),
                ('currency', models.CharField(default='USD', max_length=50, verbose_name='Currency')),
                ('bottle_size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bottle Size')),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='Stock')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Image URL')),
                ('upc', models.CharField(blank=True, max_length=255, null=True, verbose_name='UPC')),
                ('status', models.BooleanField(default=True, verbose_name='Active Status')),
                ('category', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Category')),
                ('subcategory', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Sub Category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
