# Generated by Django 3.2.5 on 2021-10-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bottle_size',
            field=models.CharField(default='', max_length=100, verbose_name='Bottle Size'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='', max_length=255, verbose_name='Brand'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='', max_length=255, verbose_name='Image URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Weight'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.IntegerField(default=2021, verbose_name='Year'),
            preserve_default=False,
        ),
    ]
