# Generated by Django 3.2.5 on 2022-09-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211006_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bottle_size',
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default='TND', max_length=50, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='products/', verbose_name='Image'),
        ),
    ]
