# Generated by Django 3.2.5 on 2022-09-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(blank=True, default='/static/images/default_product.png', null=True, upload_to='products/', verbose_name='Image'),
        ),
    ]
