# Generated by Django 3.2.5 on 2023-04-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(blank=True, default='/static/images/default_underwear.png', null=True, upload_to='products/', verbose_name='Image'),
        ),
    ]
