# Generated by Django 3.2.5 on 2023-05-10 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_marketplace_delivery_man'),
        ('products', '0020_alter_product_marketplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=255, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(default=None, upload_to='products/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='marketplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.marketplace'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='upc',
            field=models.CharField(max_length=255, verbose_name='UPC'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=6, verbose_name='Weight'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.IntegerField(default=1, verbose_name='Year'),
            preserve_default=False,
        ),
    ]
